samples:
  - name: cloudflare-rptsw
    provider: cloudflare
    api_token: os.environ.get("CLOUDFLARE_API_TOKEN")
    account_id: "rptsw_cloudflare_main" # 云账号唯一ID，如AWS账号ID等
  - name: aliyun-dns-prod
    provider: aliyun
    credentials:
      access_key: "LTAI5tB6U2TFCEtt2rw9BymS"
      secret_key: "Kol57bRDt6lx347U2aRlFXboJaPNV0"
accounts:
  - name: rptsw-aws-wy
    provider: aws
    account_id: rptsw_aws_wangyou
    profile: rptsw_
    regions: [ap-east-1]
    default_region: ap-east-1
accounts2:
   - name: rptsw-aws-cn
    provider: aws
    account_id: rptsw_aws_rptcabernet
    profile: rptsw_
    regions: [ap-east-1]
    default_region: ap-east-1

  - name: rptsw-aws-cn2
    provider: aws
    account_id: rptsw_aws_cabernethk
    profile: rptsw_
    regions: [ap-east-1]
    default_region: ap-east-1

  - name: rptsw-aws-cn3
    provider: aws
    account_id: rptsw_aws_fcmo
    profile: rptsw_
    regions: [ap-east-1]
    default_region: ap-east-1

  - name: rptsw-aws-melo
    provider: aws
    account_id: rptsw_aws_rptmelo
    profile: rptsw_
    regions: [ap-east-1]
    default_region: ap-east-1

  - name: rptsw-aws-wy
    provider: aws
    account_id: rptsw_aws_wangyou
    profile: rptsw_
    regions: [ap-east-1]
    default_region: ap-east-1

  - name: rptsw-aws-vn
    provider: aws
    account_id: rptsw_aws_rptcabernetvn
    profile: rptsw_
    regions: [ap-east-1]
    default_region: ap-east-1

  - name: rptsw-aws-vn2
    provider: aws
    account_id: rptsw_aws_cabernethcm
    profile: rptsw_
    regions: [ap-east-1]
    default_region: ap-east-1

  - name: rptsw-aws-marble
    provider: aws
    account_id: rptsw_aws_rptmarble
    profile: rptsw_
    regions: [ap-east-1]
    default_region: ap-east-1   